sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kYcs0rPo9k8eBBLT8CHyiKqi7wuVy7V5SsSA6Mww2jQ4BCADZwGu1uJ5IodxYWJGnvB6Nhq2XOf/gNeysCc9DwBpN+yEfPwk91doviNhXJ1VsL67VgFb9XxLZyhiwp/4nZamLGMRt8pVybN9z4jbZmpTI2qsAX6WvivjEIL+ZmZhWI+Lq9lGlGhc1jDwAyRN/9IYr0AvXYfZR0LJHEwcqfKmi3Jyaz6bFsAf6DL8RYX/K12oy3m/JPUM9snbd4qQ43X3m2+urFZkB9+56Ffp5cC7MxVOVzfqC7ofJsWLCmBs1xx7rJXJdYFJzgaW6bOkY6/0rc4y+t2fH3WBJVP2sasYcjUCsCLga4MasmBYdFCFMwLugU01LWQEPfTCOAT9VP/5CPiHPIKXpxnhQAkL5NreqrhHifc56QiEwBcZFcF4kGJ1oDdZ9X7XL7vDxO6wB6b1iBh32AU1bFZghv8lHtv2jaJFXTOSRlCWI7ss2SOn47OluTCKNoYX1X/7leN5KGvQh2ipDSnzt+PAMQjOOCp+EAFJaNI9Q1dlrfJx0Yq23hIvEj+UFZJ5PJwDTLPuceVs0B8WipxO1TjsgLCymVNciiYJEg/1QG6Bf3HIwRIQUpHboFJTbAtBqRIJUur8KVnAmmtNwvvvk6xhYZ0p2D03Yt0lldr5xkHKpn66Z74=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/St-George-and-St-Michael-Volume-II_5751
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy